# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_cpp <- function(q) {
    .Call(`_myTestLib_sort_cpp`, q)
}

quantile_cpp <- function(q) {
    .Call(`_myTestLib_quantile_cpp`, q)
}

